version: "3.3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./content:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
  #  links:
  #    - php
    networks:
        - code-network
    container_name: 04-02-dynamic-nginx

  php:
    image: php:8.1-fpm
    volumes:
      - ./content:/usr/share/nginx/html
    networks:
      - code-network
    container_name: 04-02-dynamic-php

networks:
    code-network:
        driver: bridge
