version: "3.3"

services:
  static:
    image: nginx:latest
    volumes:
      - ./content/static:/usr/share/nginx/html
      - ./config/static.conf:/etc/nginx/conf.d/default.conf
      - ./logs/static:/var/log/nginx
    container_name: API-static-web

  dynamic:
    image: nginx:latest
    volumes:
      - ./content/dynamic:/usr/share/nginx/html
      - ./config/dynamic.conf:/etc/nginx/conf.d/default.conf
      - ./logs/dynamic:/var/log/nginx
    container_name: API-dynamic-web

  php:
    image: php:8.1-fpm
    volumes:
      - ./content/dynamic:/usr/share/nginx/html

  reverse:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/reverse.conf:/etc/nginx/conf.d/default.conf
      - ./logs/reverse:/var/log/nginx
