version: "3.3"

# Serveur static
services:
  static:
    image: nginx:latest
    volumes:
      - ./content/static:/usr/share/nginx/html/static
      - ./config/static.conf:/etc/nginx/conf.d/default.conf
      - ./logs/static:/var/log/nginx
    container_name: API-03-static-web

# Serveur dynamic
  dynamic:
    image: nginx:latest
    links:
      - php
    volumes:
      - ./content/dynamic:/usr/share/nginx/html/dynamic
      - ./config/dynamic.conf:/etc/nginx/conf.d/default.conf
      - ./logs/dynamic:/var/log/nginx
    container_name: API-03-dynamic-web

  php:
    image: php:8.1-fpm
    container_name: API-03-dynamic-web-php
    volumes:
      - ./content/dynamic:/usr/share/nginx/html/dynamic

# Reverse-proxy
  reverse:
    image: nginx:latest
    container_name: API-03-reverse-proxy
    links:
      - static
      - dynamic
    ports:
      - "80:80"
    volumes:
      - ./content/index_reverse.html:/usr/share/nginx/html/index.html
      - ./config/reverse.conf:/etc/nginx/conf.d/default.conf
      - ./logs/reverse:/var/log/nginx
